server:
  port: 8000
spring:
  application:
    name: admin-server
  mail:
    host: smtp.sina.com
    username: adolfmc@sina.cn
    password: zhongjil11xl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: adolfmc@sina.cn
          to: 408900826@qq.com
# http://codecentric.github.io/spring-boot-admin/1.5.6/#mail-notifications
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false

